export var extCommands = {
  generate: "terminal-organizer.generate",
  open: "terminal-organizer.open",
  active: "terminal-organizer.active",
  save: "terminal-organizer.save",
  remove: "terminal-organizer.remove",
  migrate: "terminal-organizer.migrate",
  clearAll: "terminal-organizer.clear-all",
  abortAll: "terminal-organizer.abort-all",
  killAll: "terminal-organizer.kill-all",
  refresh: "terminal-organizer.refresh-activity",
  activeSessionActivity: "terminal-organizer.active-session-activity",
  importFromNPMActivity: "terminal-organizer.import-from-npm",
  importFromComposerActivity: "terminal-organizer.import-from-composer",
  importFromMakeActivity: "terminal-organizer.import-from-make",
  importFromGradleActivity: "terminal-organizer.import-from-gradle",
  importFromPipenvActivity: "terminal-organizer.import-from-pipenv",
  importFromAntActivity: "terminal-organizer.import-from-ant",
  importFromGruntActivity: "terminal-organizer.import-from-grunt",
  importFromGulpActivity: "terminal-organizer.import-from-gulp",
  sendToNewTerminalActivity: "terminal-organizer.send-to-new-terminal-activity",
  sendToCurrentTerminalActivity: "terminal-organizer.send-to-current-terminal-activity",
  copyCommandActivity: "terminal-organizer.copy-command-activity",
  collapseAllActivity: "terminal-organizer.collapse-all-activity",
  navigateActivity: "terminal-organizer.navigate-activity",
  helpAndFeedbackActivity: "terminal-organizer.help-and-feedback-activity",
  runTerminalByName: "terminal-organizer.run-terminal-by-name",
  addVariableActivity: "terminal-organizer.add-variable-activity",
  editVariableActivity: "terminal-organizer.edit-variable-activity",
  removeVariableActivity: "terminal-organizer.remove-variable-activity"
};
export var ACTIVITY_VIEW_ID = "terminalOrganizerActivityView";
export var sysCommands = {
  openFolder: "workbench.action.files.openFolder",
  openWorkspace: "workbench.action.openWorkspace",
  terminalTabFocus: "workbench.action.terminal.focus",
  terminalClear: "workbench.action.terminal.clear",
  activityCollapseAll: `workbench.actions.treeView.${ACTIVITY_VIEW_ID}.collapseAll`,
  activityRefresh: `workbench.actions.treeView.${ACTIVITY_VIEW_ID}.refresh`
};
export var constants = {
  // Common
  defaultSession: "default",
  helpAndFeedbackUrl: "https://github.com/zbychpo/vs-terminal-organizer/issues",
  // Open the configuration file
  openConfigurationFailed: "Failed to open the configuration file!",
  openWorkspace: "Please make sure to open a workspace folder before using Terminal Organizer!",
  // Generate the configuration file
  generateConfigurationTitle: "Would you like to generate the configuration?",
  generateConfigurationPlaceHolder: "Choose `Yes` if you want to generate the configuration...",
  generateConfigurationSuccess: "Generated the configuration successfully!",
  generateConfigurationFailed: "Failed to generate the configuration!",
  // Active terminal session
  selectSessionActiveTitle: "Select a session to activate",
  selectSessionActivePlaceHolder: "Select session...",
  selectFileTitle: "Select a file to import",
  selectFilePlaceHolder: "Select file...",
  activeSessionFailed: "Failed to activate the session.",
  activeTerminalFailed: "Failed to activate the terminal.",
  killTerminalFailed: "Failed to kill the terminals.",
  clearTerminalFailed: "Failed to clear the terminals.",
  abortTerminalFailed: "Failed to abort the terminals.",
  workingDirNotExist: 'The terminal "{terminal}" cannot find the current working directory "{cwd}".',
  // Valid configuration file
  selectSessionToActive: 'Please select a session to activate. The session "{session}" you choose is null or empty.',
  notExistAnySessions: "There are no sessions in the configuration file.",
  notExistAnySpitTerminal: 'There are no split terminals for the session "{session}" in the configuration file.',
  notExistAnySpitTerminalAfterFilter: 'There are no split terminals for the session "{session}" in the configuration file after removing the disabled terminals.',
  selectTerminalToActive: "Please select a terminal to activate.",
  configurationFileAlreadyExist: "A configuration file already exists, cannot generate a new one.",
  terminalWillBeDisabled: "Cannot execute terminal because the selected terminal is currently disabled.",
  groupTerminalWillBeDisabled: "Cannot execute group terminal because all terminals in the group are currently disabled.",
  // Remove the terminal session
  selectSessionRemoveTitle: "Select a session to remove:",
  selectSessionRemovePlaceHolder: "Select session...",
  notExistConfiguration: "The configuration file does not exist.",
  couldNotRemoveDefaultSession: "The default session cannot be removed.",
  removeSessionSuccess: "The session was successfully removed!",
  removeSessionFailed: "Failed to remove the session.",
  // Save the terminal session
  selectSessionSaveTitle: "Select a session to override or create a new session:",
  selectSessionSavePlaceHolder: "Select session...",
  enterSessionNameTitle: "Please enter the session name.",
  enterSessionNamePlaceHolder: "e.g. database, api",
  sessionNameNotEmpty: "Session name cannot be null or empty.",
  sessionNameIsDuplicated: "The session name already exists.",
  saveSessionSuccess: "The session was successfully saved!",
  saveSessionFailed: "Failed to save the session.",
  // Import commands
  importFileFailed: "Failed to import the command from file type {fileType}.",
  notSupportFileType: "The file type {fileType} is not supported!",
  notExistImportFile: "The file type {fileType} does not exist in any workspace {workspace}.",
  notExistAnyCommands: "There are no definition commands in the {filePath}.",
  // Migrate the configuration file
  migrateConfigurationFailed: "The attempt to upgrade to the most recent configuration file schema was unsuccessful!",
  // Run terminal by name
  selectTerminalTitle: "Select a terminal to run",
  selectTerminalPlaceHolder: "Select terminal...",
  terminalNotFound: 'Terminal "{name}" not found in session "{session}".',
  terminalNotFoundInAny: 'Terminal "{name}" not found in any session.',
  runTerminalByNameFailed: "Failed to run terminal by name.",
  // Variables
  enterVariableNameTitle: "Please enter the variable name.",
  enterVariableNamePlaceHolder: "e.g. projectRoot, logsDir",
  variableNameNotEmpty: "Variable name cannot be null or empty.",
  variableNameIsDuplicated: "A variable with this name already exists.",
  pickVariableValueTitle: "Variable value",
  pickVariableValuePlaceHolder: "e.g. H:\\Repozytoria\\vsc-terminal\\final",
  pickVariableValueButtonTooltip: "Pick a file or folder...",
  pickVariableValueDialogLabel: "Use as variable value",
  addVariableSuccess: "The variable was successfully added!",
  addVariableFailed: "Failed to add the variable.",
  editVariableFailed: "Failed to edit the variable.",
  removeVariableFailed: "Failed to remove the variable.",
  removeVariableSuccess: "The variable was successfully removed!",
  // The components
  yesButton: "Yes",
  noButton: "No",
  newSession: "Create a new session...",
  viewConfigurationButton: "View Configuration",
  openWorkspaceButton: "Open Workspace",
  openFolderButton: "Open Folder",
  viewError: "View Error"
};
